import React from 'react'

function Footer() {
  return (
    <footer className='home-footer'>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur esse eaque repellat nulla, eos quaerat saepe! Itaque facilis unde earum iure recusandae aliquam ex neque repellat adipisci, nam eius sed commodi perferendis ratione animi labore error voluptas. Quod dolorem ullam facilis libero voluptatum modi, cum at vitae blanditiis deleniti incidunt magnam hic sint quam ratione, cupiditate explicabo ipsa pariatur ea labore saepe nisi. Laboriosam non optio voluptate id nemo expedita dolore? Beatae molestias, consequatur expedita doloremque nihil est ex facere deserunt sint, blanditiis porro quisquam iure! Reiciendis reprehenderit earum veniam tempora cumque dolore, qui ducimus dolores. Molestias voluptas corporis eius numquam magnam, dolorem, veritatis cum labore ipsa enim, odio in. Rerum, dolorum. Perferendis, doloremque earum sint dolor maiores expedita ex aliquam possimus quod quae magni animi deleniti quam laborum quibusdam sunt consequatur dolorum eum eligendi natus repudiandae dignissimos numquam esse! Omnis dolor corporis recusandae nisi atque velit provident quod fuga natus optio quaerat ullam quidem nostrum molestiae, sequi et voluptatem vero. Nostrum asperiores eaque fugit ratione! Quo aut repudiandae amet consequuntur ea fugiat velit hic! Qui recusandae deleniti ut et tempore fugiat accusantium nesciunt corporis illo nihil voluptate iusto ea velit facere optio, tempora eos amet laboriosam corrupti dolorem quod, quia eligendi commodi placeat. Explicabo voluptas, placeat, odit quo eius, impedit earum quis architecto esse et praesentium. Vero, doloremque sunt cumque tempora illo est laborum aperiam! Ullam numquam atque incidunt ducimus dolorem fugiat accusamus aspernatur pariatur cupiditate, necessitatibus perspiciatis rem cumque nobis, iusto mollitia natus, excepturi vitae aliquid eaque possimus. Adipisci ullam soluta iusto! Eveniet esse magni voluptatibus ipsa, consequuntur molestiae autem, delectus quam adipisci, tempora consectetur! Cumque eligendi quae veniam quo sapiente molestias facere, corrupti voluptates minus, repudiandae laborum quos cum modi ducimus. Deleniti quasi dignissimos sequi sed error, veritatis asperiores blanditiis repellendus. Magni quo similique atque praesentium quia!</p>
    </footer>  
  )
}

export default Footer